//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DisplayItems", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate A Card.
        /// </summary>
        internal static string ActivateACard {
            get {
                return ResourceManager.GetString("ActivateACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To Put On Card.
        /// </summary>
        internal static string ActivateAmount {
            get {
                return ResourceManager.GetString("ActivateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card to activate.
        /// </summary>
        internal static string ActivateCardSwipe {
            get {
                return ResourceManager.GetString("ActivateCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string ActivateUnsuccessfull {
            get {
                return ResourceManager.GetString("ActivateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to put on the card.
        /// </summary>
        internal static string AmountToPutOnCard {
            get {
                return ResourceManager.GetString("AmountToPutOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Inquiry.
        /// </summary>
        internal static string BalanceInquiry {
            get {
                return ResourceManager.GetString("BalanceInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Balance Transfer.
        /// </summary>
        internal static string BalanceTransfer {
            get {
                return ResourceManager.GetString("BalanceTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk ID.
        /// </summary>
        internal static string ClerkID {
            get {
                return ResourceManager.GetString("ClerkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Inquiry.
        /// </summary>
        internal static string DoInquiry {
            get {
                return ResourceManager.GetString("DoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Return.
        /// </summary>
        internal static string GiftReturn {
            get {
                return ResourceManager.GetString("GiftReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Sale.
        /// </summary>
        internal static string GiftSale {
            get {
                return ResourceManager.GetString("GiftSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card for Inquiry.
        /// </summary>
        internal static string InquiryCardSwipe {
            get {
                return ResourceManager.GetString("InquiryCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty.
        /// </summary>
        internal static string Loyalty {
            get {
                return ResourceManager.GetString("Loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Return.
        /// </summary>
        internal static string LoyaltyReturn {
            get {
                return ResourceManager.GetString("LoyaltyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Used.
        /// </summary>
        internal static string LoyaltySaleCouponUsed {
            get {
                return ResourceManager.GetString("LoyaltySaleCouponUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        internal static string LoyaltySaleInvoiceNumber {
            get {
                return ResourceManager.GetString("LoyaltySaleInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID.
        /// </summary>
        internal static string MerchantID {
            get {
                return ResourceManager.GetString("MerchantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Return.
        /// </summary>
        internal static string ReturnAmount {
            get {
                return ResourceManager.GetString("ReturnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card for return.
        /// </summary>
        internal static string ReturnCardSwipe {
            get {
                return ResourceManager.GetString("ReturnCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for return.
        /// </summary>
        internal static string ReturnReason {
            get {
                return ResourceManager.GetString("ReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return an item paid for by gift card.
        /// </summary>
        internal static string ReturnValueToCard {
            get {
                return ResourceManager.GetString("ReturnValueToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Sale.
        /// </summary>
        internal static string SaleAmount {
            get {
                return ResourceManager.GetString("SaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card to sell from.
        /// </summary>
        internal static string SaleCardSwipe {
            get {
                return ResourceManager.GetString("SaleCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Sale.
        /// </summary>
        internal static string SaleDescription {
            get {
                return ResourceManager.GetString("SaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell From Card.
        /// </summary>
        internal static string SellFromCard {
            get {
                return ResourceManager.GetString("SellFromCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe a card and fill out the rest.
        /// </summary>
        internal static string SwipeAndFill {
            get {
                return ResourceManager.GetString("SwipeAndFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Up.
        /// </summary>
        internal static string TopUp {
            get {
                return ResourceManager.GetString("TopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to add to card.
        /// </summary>
        internal static string TopUpAmount {
            get {
                return ResourceManager.GetString("TopUpAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card to Top Up.
        /// </summary>
        internal static string TopUpCardSwipe {
            get {
                return ResourceManager.GetString("TopUpCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Top Up.
        /// </summary>
        internal static string TopUpDescription {
            get {
                return ResourceManager.GetString("TopUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card to Transfer From.
        /// </summary>
        internal static string TransferFromCardSwipe {
            get {
                return ResourceManager.GetString("TransferFromCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Balance Transfer.
        /// </summary>
        internal static string TransferReason {
            get {
                return ResourceManager.GetString("TransferReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card to Transfer to.
        /// </summary>
        internal static string TransferToCardSwipe {
            get {
                return ResourceManager.GetString("TransferToCardSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string VoidAmount {
            get {
                return ResourceManager.GetString("VoidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string VoidCardNumber {
            get {
                return ResourceManager.GetString("VoidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string VoidDescription {
            get {
                return ResourceManager.GetString("VoidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to void this transaction?.
        /// </summary>
        internal static string VoidQuestion {
            get {
                return ResourceManager.GetString("VoidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for the Void.
        /// </summary>
        internal static string VoidReason {
            get {
                return ResourceManager.GetString("VoidReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void This.
        /// </summary>
        internal static string VoidThis {
            get {
                return ResourceManager.GetString("VoidThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date &amp; Time.
        /// </summary>
        internal static string VoidTransactionDateTime {
            get {
                return ResourceManager.GetString("VoidTransactionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string VoidTransactionType {
            get {
                return ResourceManager.GetString("VoidTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string WasUnsuccessful {
            get {
                return ResourceManager.GetString("WasUnsuccessful", resourceCulture);
            }
        }
    }
}
