//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardHolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardHolder()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int ID { get; set; }
        public System.Guid CardHolderGUID { get; set; }
        public string EncryptedFirstName { get; set; }
        public string LastName { get; set; }
        public string EncryptedLastName { get; set; }
        public string EncryptedCardHolderName { get; set; }
        public string EncryptedAddress1 { get; set; }
        public string EncryptedAddress2 { get; set; }
        public string EncryptedCity { get; set; }
        public string State { get; set; }
        public string EncryptedPostalCode { get; set; }
        public string Country { get; set; }
        public string EncryptedPhone { get; set; }
        public string EncryptedEmail { get; set; }
        public Nullable<System.Guid> Card1 { get; set; }
        public Nullable<System.Guid> Card2 { get; set; }
        public Nullable<System.Guid> Card3 { get; set; }
        public Nullable<System.Guid> Card4 { get; set; }
        public Nullable<System.Guid> Card5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
    }
}
