//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GiftEntities : DbContext
    {
        public GiftEntities()
            : base("name=GiftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardHolder> CardHolders { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Clerk> Clerks { get; set; }
        public virtual DbSet<GiftSystem> GiftSystems { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<MerchantBilling> MerchantBillings { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
    
        public virtual ObjectResult<gp_Close_Result> gp_Close(string mID, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime)
        {
            var mIDParameter = mID != null ?
                new ObjectParameter("MID", mID) :
                new ObjectParameter("MID", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_Close_Result>("gp_Close", mIDParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter);
        }
    
        public virtual ObjectResult<gp_DailyReport_Result> gp_DailyReport(string mID, string clerk, string type, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime)
        {
            var mIDParameter = mID != null ?
                new ObjectParameter("MID", mID) :
                new ObjectParameter("MID", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_DailyReport_Result>("gp_DailyReport", mIDParameter, clerkParameter, typeParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter);
        }
    
        public virtual ObjectResult<gp_GiftActivateCard_Result> gp_GiftActivateCard(string merchant, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardToActivate, Nullable<int> newCardHolder, Nullable<decimal> amount, string invoiceNum)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("Merchant", merchant) :
                new ObjectParameter("Merchant", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardToActivateParameter = cardToActivate != null ?
                new ObjectParameter("CardToActivate", cardToActivate) :
                new ObjectParameter("CardToActivate", typeof(string));
    
            var newCardHolderParameter = newCardHolder.HasValue ?
                new ObjectParameter("NewCardHolder", newCardHolder) :
                new ObjectParameter("NewCardHolder", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var invoiceNumParameter = invoiceNum != null ?
                new ObjectParameter("InvoiceNum", invoiceNum) :
                new ObjectParameter("InvoiceNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftActivateCard_Result>("gp_GiftActivateCard", merchantParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardToActivateParameter, newCardHolderParameter, amountParameter, invoiceNumParameter);
        }
    
        public virtual ObjectResult<gp_GiftBalanceInq_Result> gp_GiftBalanceInq(string merchant, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardToFind)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("Merchant", merchant) :
                new ObjectParameter("Merchant", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardToFindParameter = cardToFind != null ?
                new ObjectParameter("CardToFind", cardToFind) :
                new ObjectParameter("CardToFind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftBalanceInq_Result>("gp_GiftBalanceInq", merchantParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardToFindParameter);
        }
    
        public virtual ObjectResult<gp_GiftReturn_Result> gp_GiftReturn(string merchant, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardNum, Nullable<decimal> creditAmount, string whyCredit, string invoiceNum)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("Merchant", merchant) :
                new ObjectParameter("Merchant", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardNumParameter = cardNum != null ?
                new ObjectParameter("CardNum", cardNum) :
                new ObjectParameter("CardNum", typeof(string));
    
            var creditAmountParameter = creditAmount.HasValue ?
                new ObjectParameter("CreditAmount", creditAmount) :
                new ObjectParameter("CreditAmount", typeof(decimal));
    
            var whyCreditParameter = whyCredit != null ?
                new ObjectParameter("WhyCredit", whyCredit) :
                new ObjectParameter("WhyCredit", typeof(string));
    
            var invoiceNumParameter = invoiceNum != null ?
                new ObjectParameter("InvoiceNum", invoiceNum) :
                new ObjectParameter("InvoiceNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftReturn_Result>("gp_GiftReturn", merchantParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardNumParameter, creditAmountParameter, whyCreditParameter, invoiceNumParameter);
        }
    
        public virtual ObjectResult<gp_GiftSaleCommon_Result> gp_GiftSaleCommon(string transType, string merchantID, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardToSellFrom, Nullable<decimal> amountOfSale, string salesDescription, string invoiceNum, Nullable<long> originalSalesTran)
        {
            var transTypeParameter = transType != null ?
                new ObjectParameter("TransType", transType) :
                new ObjectParameter("TransType", typeof(string));
    
            var merchantIDParameter = merchantID != null ?
                new ObjectParameter("MerchantID", merchantID) :
                new ObjectParameter("MerchantID", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardToSellFromParameter = cardToSellFrom != null ?
                new ObjectParameter("CardToSellFrom", cardToSellFrom) :
                new ObjectParameter("CardToSellFrom", typeof(string));
    
            var amountOfSaleParameter = amountOfSale.HasValue ?
                new ObjectParameter("AmountOfSale", amountOfSale) :
                new ObjectParameter("AmountOfSale", typeof(decimal));
    
            var salesDescriptionParameter = salesDescription != null ?
                new ObjectParameter("SalesDescription", salesDescription) :
                new ObjectParameter("SalesDescription", typeof(string));
    
            var invoiceNumParameter = invoiceNum != null ?
                new ObjectParameter("InvoiceNum", invoiceNum) :
                new ObjectParameter("InvoiceNum", typeof(string));
    
            var originalSalesTranParameter = originalSalesTran.HasValue ?
                new ObjectParameter("OriginalSalesTran", originalSalesTran) :
                new ObjectParameter("OriginalSalesTran", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftSaleCommon_Result>("gp_GiftSaleCommon", transTypeParameter, merchantIDParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardToSellFromParameter, amountOfSaleParameter, salesDescriptionParameter, invoiceNumParameter, originalSalesTranParameter);
        }
    
        public virtual ObjectResult<gp_GiftSellFromCard_Result> gp_GiftSellFromCard(string merchantID, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardToSellFrom, Nullable<decimal> amountOfSale, string salesDescription, string invoiceNum)
        {
            var merchantIDParameter = merchantID != null ?
                new ObjectParameter("MerchantID", merchantID) :
                new ObjectParameter("MerchantID", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardToSellFromParameter = cardToSellFrom != null ?
                new ObjectParameter("CardToSellFrom", cardToSellFrom) :
                new ObjectParameter("CardToSellFrom", typeof(string));
    
            var amountOfSaleParameter = amountOfSale.HasValue ?
                new ObjectParameter("AmountOfSale", amountOfSale) :
                new ObjectParameter("AmountOfSale", typeof(decimal));
    
            var salesDescriptionParameter = salesDescription != null ?
                new ObjectParameter("SalesDescription", salesDescription) :
                new ObjectParameter("SalesDescription", typeof(string));
    
            var invoiceNumParameter = invoiceNum != null ?
                new ObjectParameter("InvoiceNum", invoiceNum) :
                new ObjectParameter("InvoiceNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftSellFromCard_Result>("gp_GiftSellFromCard", merchantIDParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardToSellFromParameter, amountOfSaleParameter, salesDescriptionParameter, invoiceNumParameter);
        }
    
        public virtual ObjectResult<gp_GiftTipFromCard_Result> gp_GiftTipFromCard(string merchantID, string clerk, string whereFrom, string merchSeqNum, string terminalID, Nullable<System.DateTime> localTime, string cardToSellFrom, Nullable<decimal> amountOfTip, string salesDescription, string invoiceNum, Nullable<long> originalSaleTrans)
        {
            var merchantIDParameter = merchantID != null ?
                new ObjectParameter("MerchantID", merchantID) :
                new ObjectParameter("MerchantID", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var whereFromParameter = whereFrom != null ?
                new ObjectParameter("WhereFrom", whereFrom) :
                new ObjectParameter("WhereFrom", typeof(string));
    
            var merchSeqNumParameter = merchSeqNum != null ?
                new ObjectParameter("MerchSeqNum", merchSeqNum) :
                new ObjectParameter("MerchSeqNum", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardToSellFromParameter = cardToSellFrom != null ?
                new ObjectParameter("CardToSellFrom", cardToSellFrom) :
                new ObjectParameter("CardToSellFrom", typeof(string));
    
            var amountOfTipParameter = amountOfTip.HasValue ?
                new ObjectParameter("AmountOfTip", amountOfTip) :
                new ObjectParameter("AmountOfTip", typeof(decimal));
    
            var salesDescriptionParameter = salesDescription != null ?
                new ObjectParameter("SalesDescription", salesDescription) :
                new ObjectParameter("SalesDescription", typeof(string));
    
            var invoiceNumParameter = invoiceNum != null ?
                new ObjectParameter("InvoiceNum", invoiceNum) :
                new ObjectParameter("InvoiceNum", typeof(string));
    
            var originalSaleTransParameter = originalSaleTrans.HasValue ?
                new ObjectParameter("OriginalSaleTrans", originalSaleTrans) :
                new ObjectParameter("OriginalSaleTrans", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GiftTipFromCard_Result>("gp_GiftTipFromCard", merchantIDParameter, clerkParameter, whereFromParameter, merchSeqNumParameter, terminalIDParameter, localTimeParameter, cardToSellFromParameter, amountOfTipParameter, salesDescriptionParameter, invoiceNumParameter, originalSaleTransParameter);
        }
    
        public virtual ObjectResult<gp_InvoiceMerchant_Result> gp_InvoiceMerchant(Nullable<int> whichMerchant, Nullable<int> trialOrFinal)
        {
            var whichMerchantParameter = whichMerchant.HasValue ?
                new ObjectParameter("WhichMerchant", whichMerchant) :
                new ObjectParameter("WhichMerchant", typeof(int));
    
            var trialOrFinalParameter = trialOrFinal.HasValue ?
                new ObjectParameter("TrialOrFinal", trialOrFinal) :
                new ObjectParameter("TrialOrFinal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_InvoiceMerchant_Result>("gp_InvoiceMerchant", whichMerchantParameter, trialOrFinalParameter);
        }
    
        public virtual ObjectResult<gp_ShipCard_Result> gp_ShipCard(string merchant, string clerk, string terminalID, Nullable<System.DateTime> localTime, string cardShipped, string transText)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("Merchant", merchant) :
                new ObjectParameter("Merchant", typeof(string));
    
            var clerkParameter = clerk != null ?
                new ObjectParameter("Clerk", clerk) :
                new ObjectParameter("Clerk", typeof(string));
    
            var terminalIDParameter = terminalID != null ?
                new ObjectParameter("TerminalID", terminalID) :
                new ObjectParameter("TerminalID", typeof(string));
    
            var localTimeParameter = localTime.HasValue ?
                new ObjectParameter("LocalTime", localTime) :
                new ObjectParameter("LocalTime", typeof(System.DateTime));
    
            var cardShippedParameter = cardShipped != null ?
                new ObjectParameter("CardShipped", cardShipped) :
                new ObjectParameter("CardShipped", typeof(string));
    
            var transTextParameter = transText != null ?
                new ObjectParameter("TransText", transText) :
                new ObjectParameter("TransText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_ShipCard_Result>("gp_ShipCard", merchantParameter, clerkParameter, terminalIDParameter, localTimeParameter, cardShippedParameter, transTextParameter);
        }
    }
}
