//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long ID { get; set; }
        public System.DateTime WhenHappened { get; set; }
        public System.Guid CardGUID { get; set; }
        public System.Guid WhichMerchantGUID { get; set; }
        public Nullable<long> MerchSeqNumber { get; set; }
        public string Clerk { get; set; }
        public string WebCellOrDialup { get; set; }
        public string TerminalID { get; set; }
        public Nullable<System.DateTime> LocalTime { get; set; }
        public string TransType { get; set; }
        public string ErrorCode { get; set; }
        public string TransactionText { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> TipAmount { get; set; }
        public Nullable<decimal> TabAmount { get; set; }
        public Nullable<System.Guid> CardGUID2 { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<long> SaleTransaction { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Card Card1 { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
