//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantBilling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MerchantBilling()
        {
            this.Merchants = new HashSet<Merchant>();
        }
    
        public int ID { get; set; }
        public System.Guid MerchantBillingGUID { get; set; }
        public string CardType { get; set; }
        public string EncryptedCardNumber { get; set; }
        public Nullable<decimal> ExpiryDate { get; set; }
        public string CVV { get; set; }
        public string EncryptedRouting { get; set; }
        public string EncryptedAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merchant> Merchants { get; set; }
    }
}
