//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.Cards = new HashSet<Card>();
            this.Histories = new HashSet<History>();
        }
    
        public int ID { get; set; }
        public System.Guid MerchantGUID { get; set; }
        public string MerchantID { get; set; }
        public string MerchantName { get; set; }
        public string MerchantUserName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string email { get; set; }
        public string TimeZone { get; set; }
        public long LastSeqNumber { get; set; }
        public Nullable<System.DateTime> LastShiftClose { get; set; }
        public string GiftActive { get; set; }
        public string SplitTender { get; set; }
        public string Restaurant { get; set; }
        public string BillingCycle { get; set; }
        public System.DateTime LastBillingDate { get; set; }
        public long LastBillingNumber { get; set; }
        public Nullable<System.Guid> BillingInfo { get; set; }
        public Nullable<System.DateTime> PaidUpTo { get; set; }
        public string EncryptedTaxID { get; set; }
        public Nullable<System.Guid> PricingCol { get; set; }
        public string CurrencyCode { get; set; }
        public int AskForClerkServer { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingAddressLine3 { get; set; }
        public string ShippingAddressLine4 { get; set; }
        public string ReceiptHeaderLine1 { get; set; }
        public string ReceiptHeaderLine2 { get; set; }
        public string ReceiptHeaderLine3 { get; set; }
        public string ReceiptHeaderLine4 { get; set; }
        public string ReceiptHeaderLine5 { get; set; }
        public string ReceiptFooterLine1 { get; set; }
        public string ReceiptFooterLine2 { get; set; }
        public string BackgroundImageName { get; set; }
        public Nullable<int> ActivateAmount1 { get; set; }
        public Nullable<int> ActivateAmount2 { get; set; }
        public Nullable<int> ActivateAmount3 { get; set; }
        public Nullable<int> ActivateAmount4 { get; set; }
        public Nullable<int> ActivateAmount5 { get; set; }
        public Nullable<int> ActivateAmount6 { get; set; }
        public Nullable<int> ActivateAmount7 { get; set; }
        public Nullable<int> ActivateAmount8 { get; set; }
        public Nullable<int> ActivateAmount9 { get; set; }
        public Nullable<int> ActivateAmount10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        public virtual MerchantBilling MerchantBilling { get; set; }
        public virtual Price Price { get; set; }
    }
}
