//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_Gift_Card_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Price()
        {
            this.Merchants = new HashSet<Merchant>();
        }
    
        public int ID { get; set; }
        public System.Guid PriceGUID { get; set; }
        public string PricingName { get; set; }
        public decimal CardPrice { get; set; }
        public decimal TransactionPrice { get; set; }
        public decimal SupportTransactionPrice { get; set; }
        public decimal GiftMonthlyFee { get; set; }
        public Nullable<decimal> CardholderMonthlyFee { get; set; }
        public Nullable<int> CardHolderPercentageCharge { get; set; }
        public Nullable<int> AfterXMonths { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merchant> Merchants { get; set; }
    }
}
